alter table "public"."recommendations" drop constraint "recommendations_drawing_id_fkey1";

create table "public"."drawings" (
    "id" bigint generated by default as identity not null,
    "drawing_id" uuid default gen_random_uuid(),
    "user_id" uuid default gen_random_uuid(),
    "ai_message" text
);


alter table "public"."recommendations" drop column "artist_name";

alter table "public"."recommendations" drop column "full_track_data";

alter table "public"."recommendations" drop column "owner_id";

alter table "public"."recommendations" drop column "preview_url";

alter table "public"."recommendations" drop column "track_name";

alter table "public"."recommendations" add column "songs_id" uuid;

CREATE UNIQUE INDEX drawings_pkey ON public.drawings USING btree (id);

alter table "public"."drawings" add constraint "drawings_pkey" PRIMARY KEY using index "drawings_pkey";

alter table "public"."drawings" add constraint "drawings_drawing_id_fkey" FOREIGN KEY (drawing_id) REFERENCES storage.objects(id) not valid;

alter table "public"."drawings" validate constraint "drawings_drawing_id_fkey";

alter table "public"."recommendations" add constraint "recommendations_drawing_id_fkey" FOREIGN KEY (drawing_id) REFERENCES storage.objects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recommendations" validate constraint "recommendations_drawing_id_fkey";

alter table "public"."recommendations" add constraint "recommendations_songs_id_fkey" FOREIGN KEY (songs_id) REFERENCES songs(id) not valid;

alter table "public"."recommendations" validate constraint "recommendations_songs_id_fkey";

grant delete on table "public"."drawings" to "anon";

grant insert on table "public"."drawings" to "anon";

grant references on table "public"."drawings" to "anon";

grant select on table "public"."drawings" to "anon";

grant trigger on table "public"."drawings" to "anon";

grant truncate on table "public"."drawings" to "anon";

grant update on table "public"."drawings" to "anon";

grant delete on table "public"."drawings" to "authenticated";

grant insert on table "public"."drawings" to "authenticated";

grant references on table "public"."drawings" to "authenticated";

grant select on table "public"."drawings" to "authenticated";

grant trigger on table "public"."drawings" to "authenticated";

grant truncate on table "public"."drawings" to "authenticated";

grant update on table "public"."drawings" to "authenticated";

grant delete on table "public"."drawings" to "service_role";

grant insert on table "public"."drawings" to "service_role";

grant references on table "public"."drawings" to "service_role";

grant select on table "public"."drawings" to "service_role";

grant trigger on table "public"."drawings" to "service_role";

grant truncate on table "public"."drawings" to "service_role";

grant update on table "public"."drawings" to "service_role";


