create table "public"."drawings" (
    "id" bigint generated by default as identity not null,
    "drawing_id" uuid default gen_random_uuid(),
    "user_id" uuid default gen_random_uuid(),
    "ai_message" text,
    "drawing_url" text
);


create table "public"."recommendations" (
    "id" uuid not null default gen_random_uuid(),
    "drawing_id" uuid,
    "song_id" uuid
);


create table "public"."songs" (
    "id" uuid not null default gen_random_uuid(),
    "full_track_data" jsonb,
    "last_updated" timestamp without time zone default now()
);


CREATE UNIQUE INDEX drawings_pkey ON public.drawings USING btree (id);

CREATE UNIQUE INDEX recommendations_pkey ON public.recommendations USING btree (id);

CREATE UNIQUE INDEX songs_pkey ON public.songs USING btree (id);

alter table "public"."drawings" add constraint "drawings_pkey" PRIMARY KEY using index "drawings_pkey";

alter table "public"."recommendations" add constraint "recommendations_pkey" PRIMARY KEY using index "recommendations_pkey";

alter table "public"."songs" add constraint "songs_pkey" PRIMARY KEY using index "songs_pkey";

alter table "public"."drawings" add constraint "drawings_drawing_id_fkey" FOREIGN KEY (drawing_id) REFERENCES storage.objects(id) not valid;

alter table "public"."drawings" validate constraint "drawings_drawing_id_fkey";

alter table "public"."recommendations" add constraint "recommendations_drawing_id_fkey" FOREIGN KEY (drawing_id) REFERENCES storage.objects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recommendations" validate constraint "recommendations_drawing_id_fkey";

alter table "public"."recommendations" add constraint "recommendations_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(id) not valid;

alter table "public"."recommendations" validate constraint "recommendations_song_id_fkey";

grant delete on table "public"."drawings" to "anon";

grant insert on table "public"."drawings" to "anon";

grant references on table "public"."drawings" to "anon";

grant select on table "public"."drawings" to "anon";

grant trigger on table "public"."drawings" to "anon";

grant truncate on table "public"."drawings" to "anon";

grant update on table "public"."drawings" to "anon";

grant delete on table "public"."drawings" to "authenticated";

grant insert on table "public"."drawings" to "authenticated";

grant references on table "public"."drawings" to "authenticated";

grant select on table "public"."drawings" to "authenticated";

grant trigger on table "public"."drawings" to "authenticated";

grant truncate on table "public"."drawings" to "authenticated";

grant update on table "public"."drawings" to "authenticated";

grant delete on table "public"."drawings" to "service_role";

grant insert on table "public"."drawings" to "service_role";

grant references on table "public"."drawings" to "service_role";

grant select on table "public"."drawings" to "service_role";

grant trigger on table "public"."drawings" to "service_role";

grant truncate on table "public"."drawings" to "service_role";

grant update on table "public"."drawings" to "service_role";

grant delete on table "public"."recommendations" to "anon";

grant insert on table "public"."recommendations" to "anon";

grant references on table "public"."recommendations" to "anon";

grant select on table "public"."recommendations" to "anon";

grant trigger on table "public"."recommendations" to "anon";

grant truncate on table "public"."recommendations" to "anon";

grant update on table "public"."recommendations" to "anon";

grant delete on table "public"."recommendations" to "authenticated";

grant insert on table "public"."recommendations" to "authenticated";

grant references on table "public"."recommendations" to "authenticated";

grant select on table "public"."recommendations" to "authenticated";

grant trigger on table "public"."recommendations" to "authenticated";

grant truncate on table "public"."recommendations" to "authenticated";

grant update on table "public"."recommendations" to "authenticated";

grant delete on table "public"."recommendations" to "service_role";

grant insert on table "public"."recommendations" to "service_role";

grant references on table "public"."recommendations" to "service_role";

grant select on table "public"."recommendations" to "service_role";

grant trigger on table "public"."recommendations" to "service_role";

grant truncate on table "public"."recommendations" to "service_role";

grant update on table "public"."recommendations" to "service_role";

grant delete on table "public"."songs" to "anon";

grant insert on table "public"."songs" to "anon";

grant references on table "public"."songs" to "anon";

grant select on table "public"."songs" to "anon";

grant trigger on table "public"."songs" to "anon";

grant truncate on table "public"."songs" to "anon";

grant update on table "public"."songs" to "anon";

grant delete on table "public"."songs" to "authenticated";

grant insert on table "public"."songs" to "authenticated";

grant references on table "public"."songs" to "authenticated";

grant select on table "public"."songs" to "authenticated";

grant trigger on table "public"."songs" to "authenticated";

grant truncate on table "public"."songs" to "authenticated";

grant update on table "public"."songs" to "authenticated";

grant delete on table "public"."songs" to "service_role";

grant insert on table "public"."songs" to "service_role";

grant references on table "public"."songs" to "service_role";

grant select on table "public"."songs" to "service_role";

grant trigger on table "public"."songs" to "service_role";

grant truncate on table "public"."songs" to "service_role";

grant update on table "public"."songs" to "service_role";


